---
-  hosts: mywebserver
   become: yes
   tasks:
   - name: install java on ubuntu nodes
     apt:
       name: "{{myjavapakonubuntu}}"
       state: present
     when: ansible_os_family== "Debian"


   - name: install java on redhat nodes
     yum:
       name: "{{myjavapackonredhat}}"
       state: present
     when: ansible_os_family=="RedHat"